Repository nasa/HK, pull requests merged in 2022-06, with the labels that each got.

#14 Fix #13, Remove CFE_PSP_MemSet use for addresses in RAM
  fsw/src/hk_utils.c
  unit-test/utilities/hk_test_utils.c
Labels: CCB:Approved

#16 Fix #15, Updates CLA information for Apache 2.0
  .github/pull_request_template.md
  CONTRIBUTING.md
  docs/Corp_CLA_HK_250.pdf
  docs/Indv_CLA_HK_250.pdf
Labels: docs, CCB:Approved

#17 Fix #12, added codeql-build.yml
  .github/workflows/codeql-build.yml
Labels: CCB:Approved, dependency
